String data_privecy =
    'Your privacy is important to us. This Privacy Policy explains how Blood Fighter  collects, uses, and protects your personal information when you use our application. \nPersonal Information: We may collect personal information such as your name, contact number, and email address when you register or use our service.';
String about =
    'The development of this blood donation app  is a response to a critical healthcare challenge. Bloodshortage is a recurring issue that can have life-threatening consequences for patients in need of blood transfusions. \nIn this context, this app aims to bridge the gap between willing donors and individuals or medical facilities requiring blood.';
String smoking =
    'Smoking is a leading cause of cancer, contributing to various types such as lung, throat, and mouth cancer. The harmful chemicals in tobacco smoke damage DNA, leading to the uncontrolled growth of abnormal cells. Carcinogens present in cigarettes increase the risk of mutations, making smoking a primary risk factor for cancer development. Quitting smoking significantly reduces the likelihood of cancer and improves overall health. Public awareness and tobacco cessation efforts play a crucial role in preventing the devastating impact of smoking-related cancers.';
String bloodDonationBenefits =
    '1.রক্তদানের প্রথম এবং প্রধান কারণ: একজনের দানকৃত রক্ত আরেকজন মানুষের জীবন বাঁচাবে।\n2.রক্তদান স্বাস্থ্যের জন্য অত্যন্ত উপকারী। রক্তদান করার সঙ্গে সঙ্গে শরীরের মধ্যে অবস্থিত ‘বোন ম্যারো’ নতুন কণিকা তৈরির জন্য উদ্দীপ্ত হয় এবং রক্তদানের ২ সপ্তাহের মধ্যে নতুন রক্তকণিকার জন্ম হয়ে ঘাটতি পূরণ হয়ে যায়। বছরে ৩ বার রক্তদান আপনার শরীরে লোহিত কণিকাগুলোর প্রাণবন্ততা বাড়িয়ে তোলার সাথে সাথে নতুন কণিকা তৈরির হার বাড়িয়ে দেয়। উল্লেখ্য রক্তদান করার মাত্র ৪৮ ঘণ্টার মধ্যেই দেহে রক্তের পরিমাণ স্বাভাবিক হয়ে যায়।\n3. নিয়মিত রক্তদান করলে হৃদরোগ ও হার্ট অ্যাটাকের ঝুঁকি অনেকটাই কমে যায়।';
String criteria =
    '1.১৮ থেকে ৬০ বছর বয়সী যেকোনো শারীরিক ও মানসিকভাবে সুস্থ ও সক্ষম ব্যক্তি রক্ত দিতে পারবেন। \n2.যাদের ওজন ৫০ কেজি বা তার বেশি (কখনো সর্বনিম্ন ওজন ৪৫ কেজিও ধরা হয়)। \n3.কোনো ব্যক্তি একবার রক্ত দেওয়ার ৪ মাস পর আবার রক্ত দিতে পারবেন';
String mythfacts = 'ভুল ধারণা 1: রক্তদান ঝুঁকিপূর্ণ এবং দুর্বলতা হতে পারে। \nতথ্য: রক্তদান নিরাপদ এবং দাতাকে দুর্বল করে না। শরীর দ্রুত রক্ত পূর্ণ করে,\nভুল ধারণা 2: যাদের ট্যাটু আছে তারা রক্ত দিতে পারে না.\nতথ্য: যাদের ট্যাটু আছে তারা  রক্ত দান করতে পারেন, যদি এটি একটি লাইসেন্সপ্রাপ্ত সুবিধার মধ্যে করা হয় এবং নির্দিষ্ট স্বাস্থ্যবিধি এবং নিরাপত্তা মান পূরণ করে করা হয় ।\nভুল ধারণা 3: রক্তদানের ফলে দাতা রোগে আক্রান্ত হতে পারেন।\nতথ্য: রক্তদান একটি জীবাণুমুক্ত প্রক্রিয়া, এবং সমস্ত সরঞ্জাম নিষ্পত্তিযোগ্য। দানের মাধ্যমে এইচআইভি বা হেপাটাইটিসের মতো রোগে আক্রান্ত হওয়ার ঝুঁকি নেই।\nভুল ধারণা 4: রক্তদান সময়সাপেক্ষ।\nতথ্য: রক্ত দানের জন্য প্রক্রিয়াটি সাধারণত প্রায় 10-15 মিনিট সময় নেয়।অ্যাপয়েন্টমেন্ট , নিবন্ধন এবং বিশ্রাম সহ সম্পূর্ণ সাধারণত এক ঘন্টার মধ্যে স্থায়ী হয়।';