// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUOaHOV4RqdJeDEQ_3Gm2ty5AxUlRr8RY',
    appId: '1:455166254173:web:804e2bb171f4a0716e41b4',
    messagingSenderId: '455166254173',
    projectId: 'test-flutter-a0656',
    authDomain: 'test-flutter-a0656.firebaseapp.com',
    databaseURL: 'https://test-flutter-a0656-default-rtdb.firebaseio.com',
    storageBucket: 'test-flutter-a0656.appspot.com',
    measurementId: 'G-173F720RTJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChFm7h4xhIKLgC5Yblpafgd-UW2fxgDtw',
    appId: '1:455166254173:android:44dab523b985a6626e41b4',
    messagingSenderId: '455166254173',
    projectId: 'test-flutter-a0656',
    databaseURL: 'https://test-flutter-a0656-default-rtdb.firebaseio.com',
    storageBucket: 'test-flutter-a0656.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9PL3E2OFbqGt0UW9Az1e5rKXhtwl0wfg',
    appId: '1:455166254173:ios:294fa3d6e99405c76e41b4',
    messagingSenderId: '455166254173',
    projectId: 'test-flutter-a0656',
    databaseURL: 'https://test-flutter-a0656-default-rtdb.firebaseio.com',
    storageBucket: 'test-flutter-a0656.appspot.com',
    iosClientId: '455166254173-cv58jbmq1evi97hn6b9u41qs4sospu1l.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodHeroes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9PL3E2OFbqGt0UW9Az1e5rKXhtwl0wfg',
    appId: '1:455166254173:ios:a3cce513c6e663e26e41b4',
    messagingSenderId: '455166254173',
    projectId: 'test-flutter-a0656',
    databaseURL: 'https://test-flutter-a0656-default-rtdb.firebaseio.com',
    storageBucket: 'test-flutter-a0656.appspot.com',
    iosClientId: '455166254173-6q5h7kn9tfjot961fc48m51smu48l8b9.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodHeroes.RunnerTests',
  );
}
